import { FilesProps } from "../utils/Interfaces";

export interface UserDTO {
  id_user: number,
  corp: string,
  id_corp: number,
  created: string,
  nome: string,
  email: string,
  fone: string,
  user_type: string,
  disk_size: number,
  influencer_id: number,
  nivel_edit: string,
  origem: string,
  id_origem: number,
  last_login: string,
  avatar: string,
  id_grupo: number,
  status: string,
  stripe_id: string;
  assinante: string,
  saldo: number,
  saldoFormatted: string,
  credito: number,
  debito: number,
  blocked: number,
  uso_mb: number,
  usoPercentual: number,
  usoArred: number,
  push_token: string,
  qtd_files: number,
  files: FilesProps,
}